### ISSUE TITLE
Add widget for content tracking (names)

### ISSUE THREAD

**Issue by brotkrueml** [brotkrueml/typo3-matomo-widgets#8]
- [x] A widget for content tracking of names is available.
- [x] The widget can be activates/deactivated in the site configuration.
- [x] The result is displayed as a table in the widget with the columns: label, nb_impressions, interaction_rate.
- [x] The rows are sorted by nb_impressions. The sorting can be overriden in the Services file.
- [x] A maximum of 50 rows is displayed. This value can be overridden in a Services file.
- [x] The documentation is adjusted.
- [x] A feature entry to the changelog is added.

Example for the API call: https://demo.matomo.cloud/?module=API&method=Contents.getContentNames&idSite=1&period=day&date=yesterday&format=JSON&token_auth=anonymous
